version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    working_dir: /backend
    ports:
      - "5050:5000"
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/static:/etc/nginx/static
      - ./certs:/etc/nginx/certs
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "443:443"
    depends_on:
      - backend
      