version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    working_dir: /backend
    ports:
      - "5050:5000"
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/static:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"
    depends_on:
      - backend
      