"""Change tag column to User

Revision ID: 153cef0bd665
Revises: c0911c483503
Create Date: 2025-09-12 13:32:18.195074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153cef0bd665'
down_revision: Union[str, Sequence[str], None] = 'c0911c483503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('name'), table_name='tags')
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.create_index(op.f('name'), 'tags', ['name'], unique=True)
    # ### end Alembic commands ###
